/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    programmes: Programme;
    sectors: Sector;
    'case-studies': CaseStudy;
    clients: Client;
    'value-props': ValueProp;
    faqs: Faq;
    gallery: Gallery;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    programmes: ProgrammesSelect<false> | ProgrammesSelect<true>;
    sectors: SectorsSelect<false> | SectorsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    'value-props': ValuePropsSelect<false> | ValuePropsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site: Site;
    home: Home;
    pages: Page;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes".
 */
export interface Programme {
  id: number;
  title: string;
  /**
   * URL segment. Leave blank to auto-fill from "title".
   */
  slug?: string | null;
  short?: string | null;
  description?: string | null;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  imageAlt?: string | null;
  audience?: string | null;
  format?: string | null;
  certification?: string | null;
  /**
   * Sort order — lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors".
 */
export interface Sector {
  id: number;
  name: string;
  /**
   * URL segment. Leave blank to auto-fill from "name".
   */
  slug?: string | null;
  title?: string | null;
  intro?: string | null;
  metaDescription?: string | null;
  image?: (number | null) | Media;
  imageAlt?: string | null;
  programmes?: (number | Programme)[] | null;
  clients?: (number | Client)[] | null;
  /**
   * Sort order — lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  /**
   * URL segment. Leave blank to auto-fill from "name".
   */
  slug?: string | null;
  sector?: string | null;
  context?: string | null;
  /**
   * Sort order — lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  client: string;
  /**
   * URL segment. Leave blank to auto-fill from "client".
   */
  slug?: string | null;
  sector?: string | null;
  location?: string | null;
  year?: string | null;
  title?: string | null;
  summary?: string | null;
  overview?: string | null;
  delivered?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  outcomes?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  services?: (number | Programme)[] | null;
  image?: (number | null) | Media;
  imageAlt?: string | null;
  gallery?:
    | {
        image?: (number | null) | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  realPhotos?: boolean | null;
  featured?: boolean | null;
  /**
   * Sort order — lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "value-props".
 */
export interface ValueProp {
  id: number;
  title: string;
  /**
   * URL segment. Leave blank to auto-fill from "title".
   */
  slug?: string | null;
  description?: string | null;
  /**
   * Sort order — lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer?: string | null;
  /**
   * Sort order — lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  caption: string;
  alt?: string | null;
  mediaType: 'image' | 'video';
  image?: (number | null) | Media;
  provider?: ('youtube' | 'vimeo' | 'file') | null;
  videoSrc?: string | null;
  poster?: (number | null) | Media;
  /**
   * Video frame width
   */
  width?: number | null;
  /**
   * Video frame height
   */
  height?: number | null;
  /**
   * Sort order — lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'programmes';
        value: number | Programme;
      } | null)
    | ({
        relationTo: 'sectors';
        value: number | Sector;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'value-props';
        value: number | ValueProp;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes_select".
 */
export interface ProgrammesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  short?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  image?: T;
  imageAlt?: T;
  audience?: T;
  format?: T;
  certification?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors_select".
 */
export interface SectorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  title?: T;
  intro?: T;
  metaDescription?: T;
  image?: T;
  imageAlt?: T;
  programmes?: T;
  clients?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  client?: T;
  slug?: T;
  sector?: T;
  location?: T;
  year?: T;
  title?: T;
  summary?: T;
  overview?: T;
  delivered?:
    | T
    | {
        item?: T;
        id?: T;
      };
  outcomes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  services?: T;
  image?: T;
  imageAlt?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  realPhotos?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sector?: T;
  context?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "value-props_select".
 */
export interface ValuePropsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  caption?: T;
  alt?: T;
  mediaType?: T;
  image?: T;
  provider?: T;
  videoSrc?: T;
  poster?: T;
  width?: T;
  height?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  name?: string | null;
  shortName?: string | null;
  legalName?: string | null;
  tagline?: string | null;
  description?: string | null;
  email?: string | null;
  phonePrimary?: string | null;
  phoneSecondary?: string | null;
  /**
   * Digits only, e.g. 23273077004
   */
  whatsapp?: string | null;
  addressCity?: string | null;
  addressRegion?: string | null;
  addressCountry?: string | null;
  hours?: string | null;
  leadership?:
    | {
        name?: string | null;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  heroEyebrowAccent?: string | null;
  heroEyebrowRest?: string | null;
  heroTitleLine1?: string | null;
  heroTitleAccent?: string | null;
  heroTitleLine2?: string | null;
  heroSubhead?: string | null;
  heroPillTitle?: string | null;
  heroPillSubtitle?: string | null;
  clientsLabel?: string | null;
  programmesEyebrow?: string | null;
  programmesHeading?: string | null;
  programmesIntro?: string | null;
  certPathEyebrow?: string | null;
  certPathHeading?: string | null;
  certPathIntro?: string | null;
  certPathSteps?:
    | {
        title?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  whyUsEyebrow?: string | null;
  whyUsHeading?: string | null;
  whyUsIntro?: string | null;
  whyUsImageCaption?: string | null;
  workEyebrow?: string | null;
  workHeading?: string | null;
  galleryEyebrow?: string | null;
  galleryHeading?: string | null;
  faqEyebrow?: string | null;
  faqHeading?: string | null;
  statementQuote?: string | null;
  statementPartnersLabel?: string | null;
  statementPartners?:
    | {
        partner?: string | null;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  about?: {
    metaDescription?: string | null;
    heroEyebrow?: string | null;
    heroTitleLine1?: string | null;
    heroTitleLine2?: string | null;
    heroIntro?: string | null;
    storyEyebrow?: string | null;
    storyHeading?: string | null;
    storyBlocks?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    storyImageCaption?: string | null;
    leadershipEyebrow?: string | null;
    leadershipHeading?: string | null;
    locationsEyebrow?: string | null;
    locationsHeading?: string | null;
    locations?:
      | {
          place?: string | null;
          note?: string | null;
          id?: string | null;
        }[]
      | null;
    clientsHeading?: string | null;
  };
  contact?: {
    heroEyebrow?: string | null;
    heroTitle?: string | null;
    heroIntro?: string | null;
    detailsEyebrow?: string | null;
    detailsHeading?: string | null;
  };
  servicesHero?: {
    metaDescription?: string | null;
    eyebrow?: string | null;
    title?: string | null;
    intro?: string | null;
  };
  portfolioHero?: {
    metaDescription?: string | null;
    eyebrow?: string | null;
    title?: string | null;
    intro?: string | null;
  };
  galleryHero?: {
    metaDescription?: string | null;
    eyebrow?: string | null;
    title?: string | null;
    intro?: string | null;
  };
  sectorsHero?: {
    metaDescription?: string | null;
    eyebrow?: string | null;
    title?: string | null;
    intro?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  legalName?: T;
  tagline?: T;
  description?: T;
  email?: T;
  phonePrimary?: T;
  phoneSecondary?: T;
  whatsapp?: T;
  addressCity?: T;
  addressRegion?: T;
  addressCountry?: T;
  hours?: T;
  leadership?:
    | T
    | {
        name?: T;
        role?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroEyebrowAccent?: T;
  heroEyebrowRest?: T;
  heroTitleLine1?: T;
  heroTitleAccent?: T;
  heroTitleLine2?: T;
  heroSubhead?: T;
  heroPillTitle?: T;
  heroPillSubtitle?: T;
  clientsLabel?: T;
  programmesEyebrow?: T;
  programmesHeading?: T;
  programmesIntro?: T;
  certPathEyebrow?: T;
  certPathHeading?: T;
  certPathIntro?: T;
  certPathSteps?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  whyUsEyebrow?: T;
  whyUsHeading?: T;
  whyUsIntro?: T;
  whyUsImageCaption?: T;
  workEyebrow?: T;
  workHeading?: T;
  galleryEyebrow?: T;
  galleryHeading?: T;
  faqEyebrow?: T;
  faqHeading?: T;
  statementQuote?: T;
  statementPartnersLabel?: T;
  statementPartners?:
    | T
    | {
        partner?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  about?:
    | T
    | {
        metaDescription?: T;
        heroEyebrow?: T;
        heroTitleLine1?: T;
        heroTitleLine2?: T;
        heroIntro?: T;
        storyEyebrow?: T;
        storyHeading?: T;
        storyBlocks?:
          | T
          | {
              text?: T;
              id?: T;
            };
        storyImageCaption?: T;
        leadershipEyebrow?: T;
        leadershipHeading?: T;
        locationsEyebrow?: T;
        locationsHeading?: T;
        locations?:
          | T
          | {
              place?: T;
              note?: T;
              id?: T;
            };
        clientsHeading?: T;
      };
  contact?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroIntro?: T;
        detailsEyebrow?: T;
        detailsHeading?: T;
      };
  servicesHero?:
    | T
    | {
        metaDescription?: T;
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  portfolioHero?:
    | T
    | {
        metaDescription?: T;
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  galleryHero?:
    | T
    | {
        metaDescription?: T;
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  sectorsHero?:
    | T
    | {
        metaDescription?: T;
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}